### PR TITLE
Fixed compilation errors on linux (GCC & Clang)

### PR DESCRIPTION
**Pull request by 333fps**
Hi Dustin, here is a PR to fix build error on linux.

Fixed compilation errors on linux (GCC & Clang):
* '__debugbreak()' is only valid on windows, added 'raise( SIGTRAP )' which is more or less the linux equivalent.
*  Even if msvc accepts it, it is normally not allowed (compiler error) to create a forward declared unique_ptr if its destructor is inlined/defaulted.

Other:
* added virtual destructor for 'TilemapDisplay'.
* fixed typos (mine :) ) in 'README.md'.

Compiles with GCC 11.3.0, GCC 12.2.0, Clang 16.0.6 on Debian.

### CODE REVIEW

**Comment by dwjclark11** [comment]
Thanks @333fps. I am so used to using MSVC, that I forget that some things do not work correctly in linux. I appreciate the help.

Approved!

**Comment by 333fps** [comment]
You're welcome ;)
